export const POLITICAL_PREFIX = [
	'Techno-',
	'Crypto-',
	'Anarcho-',
	'Geo-',
	'Eco-',
	'Moderate ',
	'Radical ',
	'Progressive ',
	'Regressive ',
	'Constitutional ',
	'Revolutionary ',
	'Agrarian ',
	'Socio-',
	'Neo-',
	'Popular ',
	'United ',
	'Anti-',
	'Independent ',
	'Patriotic ',
	'Colonial ',
	'Xeno-',
	'Deutero-',
	'Pan-',
	'Post-',
	'Alt-',
	'Counter-',
	'Ethno-',
	'Ergato-',
	'Partheno-',
	'Sub-',
	'Fundibular ',
	'Ecclesiastic ',
	'Right And Proper ',
	'Pseudo-',
	'Paleo-',
	'Provisionary '
];

export const POLITICAL_PARTY_NAME = [
	'Socialist',
	'Democratic',
	'Republican',
	'Monarchist',
	'Communist',
	'Fascist',
	'Libertarian',
	'Unionist',
	'Particularist',
	'Nationalist',
	'Separatist',
	'Centrist',
	'Imperialist',
	'Populist',
	'Traditionalist',
	'Spartacist',
	'Confederate',
	'Federalist',
	'Survivalist',
	'Dominionist',
	'Heritagist',
	'Marxist',
	'Trotskyist',
	'Immortalist',
	'Bolshevist',
	'Menshevist',
	'Pacifist',
	'Loyalist',
	'Legislaturist',
	'Rationalist',
	'Originalist',
	'Reformist',
	'Nativist',
	'Expansionist',
	'Abolitionist',
	'Capitalist',
	'Corporatist',
	'Materialist',
	'Egoist',
	'Absolutist',
	'Consumerist',
	'Situationist',
	'Dogmatist',
	'Libertine',
	'Isolationist',
	'Accelerationist',
	'Statist'
];